[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 921600
upload_speed = 921600

lib_deps =
    hideakitai/ESP32SPISlave@^0.4.0

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_CDC_ON_BOOT=0
